#!/usr/bin/env python3

# import meshio
import matplotlib.pyplot as plt
import matplotlib.animation as anim
from matplotlib.collections import PolyCollection
import numpy as np

def read_tecplot(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()

    # Find the start of the data
    data_start = False
    data = []
    
    i = 0
    j = 0
    for line in lines:
        if line.startswith("ZONE"):
            data_start = True
            vars = line.split("=")
            for vari in range(len(vars)):
                if vars[vari].endswith('I'):
                    i = vars[vari + 1][0]
                if vars[vari].endswith('J'):
                    j = vars[vari + 1][0]
            continue
        if data_start and not line == '\n':
            # Split the line into floats and append to data
            if j != 0:
                xs = list(map(float, line.split()))
                data.append([xs[0], xs[1]])
            #    ys = list(map(float, line.split()))
            else:
                data.append(list(map(float, line.split())))

    return np.array(data)

def make_anim(folder, prefix, n):
    plt.cla()
    imgs = []

    fig, ax = plt.subplots(1,1)

    for i in range(n):
        data = read_tecplot(f'{folder}/{prefix}{i}.dat')
        x = data[:, 0]
        y = data[:, 1]

        img = ax.plot(x, y, c='b')
        imgs.append(img)
    
    ani = anim.ArtistAnimation(fig, imgs)
    ani.save(f'imgs/{prefix}.gif')

def save_imgs(folder):
    plt.cla()
    for i in range(51):

        data = read_tecplot(f'{folder}/soln{i}.dat')
        x = data[:, 0]
        y = data[:, 1]

        plt.plot(x, y)
        plt.savefig(f'imgs/soln{i}.png')

def plot_errors(folder, n):
    plt.cla()
    imgs = []

    fig, ax = plt.subplots(1,1)

    for i in range(n):
        data = read_tecplot(f'{folder}/error{i}.dat')
        x = data[:, 0]
        norm = data[:, 1]
        err = data[:, 2]

        # img = ax.plot(x, norm, label="norm")
        img = ax.plot(x, err, label="error")
        # plt.legend()

        imgs.append(img)
    
    ani = anim.ArtistAnimation(fig, imgs)
    ani.save(f'imgs/error.gif')

def make_mesh_anim(folder, prefix, n):
    plt.cla()
    imgs = []

    fig, ax = plt.subplots(1,1)

    for i in range(n):
        data = read_tecplot(f"{folder}/{prefix}{i}.dat")
        x = data[:, 0]
        y = data[:, 1]

        img = ax.scatter(x, y, marker=".", c='b', linewidths=0.2)
        imgs.append([img])
    
    ani = anim.ArtistAnimation(fig, imgs)
    ani.save(f'imgs/{prefix}.gif')
    # plt.savefig("trial_mesh.png")



if __name__ == '__main__':
    n = 240
    make_anim('RESLT', 'interface_soln', n)
    make_mesh_anim('RESLT', 'soln', n)
    # plot_errors('RESLT', 501)
    # save_imgs('RESLT')

    

    # plt.savefig('test.png')



    # file = 'vtus/soln0.vtu'

    # mesh = meshio.read(file)

    # x = mesh.points[:,0]
    # y = mesh.points[:,1]
    # z = mesh.point_data['V1']

    # plt.plot(z)
    # plt.show()

    # plt.contourf(x, y, z)
    # plt.savefig('soln0.png')