#!/usr/bin/env python3

# import meshio
import matplotlib.pyplot as plt
import matplotlib.animation as anim
import numpy as np

def read_tecplot(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()

    # Find the start of the data
    data_start = False
    data = []

    for line in lines:
        if line.startswith("ZONE"):
            data_start = True
            continue
        if data_start:
            # Split the line into floats and append to data
            data.append(list(map(float, line.split())))

    return np.array(data)

def make_anim(folder, prefix, n):
    print(f"Making animation {prefix}")
    plt.cla()
    imgs = []

    fig, ax = plt.subplots(1,1)

    for i in range(n):
        data = read_tecplot(f'{folder}/{prefix}{i}.dat')
        x = data[:, 0]
        y = data[:, 1]

        img = ax.plot(x, y, c='b')
        imgs.append(img)
    
    ani = anim.ArtistAnimation(fig, imgs)
    ani.save(f'imgs/{prefix}.gif')

def save_imgs(folder):
    plt.cla()
    for i in range(51):

        data = read_tecplot(f'{folder}/soln{i}.dat')
        x = data[:, 0]
        y = data[:, 1]

        plt.plot(x, y)
        plt.savefig(f'imgs/soln{i}.png')

def plot_errors(folder, n):
    print(f"Plotting errors")
    plt.cla()
    imgs = []

    fig, ax = plt.subplots(1,1)

    for i in range(n):
        data = read_tecplot(f'{folder}/error{i}.dat')
        x = data[:, 0]
        norm = data[:, 1]
        err = data[:, 2]

        # img = ax.plot(x, norm, label="norm")
        img = ax.plot(x, err, label="error")
        # plt.legend()

        imgs.append(img)
    
    ani = anim.ArtistAnimation(fig, imgs)
    ani.save(f'imgs/error.gif')


if __name__ == '__main__':
    n = 100
    make_anim('RESLT', 'soln', n)
    make_anim('RESLT', 'exact_soln', n)
    plot_errors('RESLT', n)
    # save_imgs('RESLT')
    

    # plt.savefig('test.png')



    # file = 'vtus/soln0.vtu'

    # mesh = meshio.read(file)

    # x = mesh.points[:,0]
    # y = mesh.points[:,1]
    # z = mesh.point_data['V1']

    # plt.plot(z)
    # plt.show()

    # plt.contourf(x, y, z)
    # plt.savefig('soln0.png')