#!/usr/bin/env python3

import os
from argparse import ArgumentParser

from run import Run

if __name__ == '__main__':
	parser = ArgumentParser()

	parser.add_argument(
		'prog',
		type=str,
		help="Name of program to run"
	)

	parser.add_argument('--name',
		type=str,
		dest='dname',
		default=None,
		help='Name of directory to store data'
	)

	parser.add_argument('--xs', '--x',
		nargs='+', 
		type=int,
		dest='xs',
		default=2,
		help="NNode per elements in one dimension to simulate with, accepts multiple arguments to be in a list"
	)

	parser.add_argument('--ts', '--t',
		nargs='+', 
		type=int,
		dest='ts',
		default=1,
		help="Order of timestepper to simulate with, accepts multiple in list"
	)

	parser.add_argument('--nxs', '--nx',
		nargs='+', 
		type=int,
		dest='nxs',
		default=10,
		help='Number of elements to simulate with, accepts multiple in list'
	)

	parser.add_argument('--dts', '--dt',
		nargs='+', 
		type=float,
		dest='dts',
		default=1e-2,
		help='timesteps to simulate with, accepts multiple in list'
	)

	parser.add_argument('--tsteps', 
		type=int,
		default=100,
		help='Number of timesteps to simulate for, only single number'
	)

	parser.add_argument('--type',
		type=str,
		choices=['a', 'x', 't', 'b', 's', 'ax', 'at', 'ab', 'as'],
		dest='dxdt',
		default='a',
		help="Type of analysis to perform a: standard run\nx: vary dx\nt: vary dt\ns: sensitivity analysis"
	)
	
	parser.add_argument('--ref',
		type=str,
		dest='reference',
		default=None,
		help='Reference run to compare against for analysys'
	)

	parser.add_argument('--nthreads',
		type=int,
		choices=range(1,os.cpu_count()),
		default=os.cpu_count(),
		help='Number of processes that can be started'
	)

	parser.add_argument('--debug',
		action='store_true',
		default=False,
		help="Use this flag to compile faster with debug flags"
	)

	parser.add_argument('--tshift',
		type=float,
		dest='tshift',
		default=0.0,
		help='time to start from'
	)

	parser.add_argument('--k1',
		type=float,
		dest='k1',
		default=1.0,
		help='Phase 1 thermal conductivity'
	)

	parser.add_argument('--k2',
		type=float,
		dest='k2',
		default=0.5,
		help='Phase 2 thermal conductivity'
	)

	parser.add_argument('--rho1',
		type=float,
		dest='rho1',
		default=1.0,
		help='Phase 1 density'
	)

	parser.add_argument('--rho2',
		type=float,
		dest='rho2',
		default=0.5,
		help='Phase 2 density'
	)

	parser.add_argument('--cp1',
		type=float,
		dest='cp1',
		default=1.0,
		help='Phase 1 specific heat capacity'
	)

	parser.add_argument('--cp2',
		type=float,
		dest='cp2',
		default=0.5,
		help='Phase 2 specific heat capacity'
	)

	parser.add_argument('--L',
		type=float,
		dest='L',
		default=1.0,
		help='Latent heat of fusion'
	)

	parser.add_argument('--eps',
		type=float,
		dest='eps',
		default=1e-6,
		help='factor to adjsut values for sensitivity analysis'
	)

	parser.add_argument('--style',
		type=str,
		dest='stylef',
		default='pltstyle.mplstyle',
		help='Stylesheet for matplotlib'
	)

	args = parser.parse_args()
	run = Run(**vars(args))