#!/usr/bin/env python3

import os
from argparse import ArgumentParser

from run import Run

if __name__ == '__main__':
	parser = ArgumentParser()

	parser.add_argument(
		'prog',
		type=str,
		help="Name of program to run"
	)

	parser.add_argument('--xs', '--x',
		nargs='+', 
		type=int,
		dest='xs',
		default=2,
		help="NNode per elements to simulate with, accepts multiple arguments to be in a list"
	)

	parser.add_argument('--ts', '--t',
		nargs='+', 
		type=int,
		dest='ts',
		default=1,
		help="Order of timestepper to simulate with, accepts multiple in list"
	)

	parser.add_argument('--nxs', '--nx',
		nargs='+', 
		type=int,
		dest='nxs',
		default=10,
		help='Number of elements to simulate with, accepts multiple in list'
	)

	parser.add_argument('--dts', '--dt',
		nargs='+', 
		type=float,
		dest='dts',
		default=1e-2,
		help='timesteps to simulate with, accepts multiple in list'
	)

	parser.add_argument('--tsteps', 
		type=int,
		default=100,
		help='Number of timesteps to simulate for, only single number'
	)

	parser.add_argument('--type',
		type=str,
		choices=['a', 'x', 't', 'b', 'ax', 'at', 'ab'],
		dest='dxdt',
		default='a',
		help="Type of analysis to perform a: standard run\nx: vary dx\nt: vary dt"
	)

	parser.add_argument('--nthreads',
		type=int,
		choices=range(1,os.cpu_count()),
		default=os.cpu_count(),
		help='Number of processes that can be started'
	)

	parser.add_argument('--debug',
		action='store_true',
		default=False,
		help="Use this flag to compile faster with debug flags"
	)

	args = parser.parse_args()
	run = Run(**vars(args))