#!/bin/bash

# Basic run script, expects two input arguments
# 	first one should be the name of the program being built by make
# 	The second is the number of steps this solver will run for


if [[ $# != 2 ]]
then
	echo "Not enough arguments, exiting ..."
	exit 1
fi

make $1

if [[ $? != 0 ]]
then
	echo "Make failed"
	exit 2
fi

rm -rf RESLT/*

for i in 10 100
do
	./$1 --nx $i --dt 0.01 --tsteps $2 | tee RESLT/$i.stdout &

	if [[ $? != 0 ]]
	then
		echo "Run failed"
		exit 3
	fi
done

./visualizer $1 $2