#!/bin/bash

# Basic run script, expects two input arguments
# 	first one should be the name of the program being built by make
# 	The second is the number of steps this solver will run for


if [[ $# != 2 ]]
then
	echo "Not enough arguments, exiting ..."
	exit 1
fi

make $1

if [[ $? != 0 ]]
then
	echo "Make failed"
	exit 2
fi

rm -rf RESLT/*

dt=0.0001
nx=100
tshift=0.5

# for nx in 5 10 50 80 100 500 800 1000 5000 # 10000
for dt in 1e-1 1e-2 1e-3 1e-4 1e-5
do
	echo -e "Running $1 with nx=$nx\t\tdt=$dt"
	./$1 --nx $nx --dt $dt --tshift $tshift --tsteps $2 >> RESLT/n$nx\_t$dt.stdout &

	if [[ $? != 0 ]]
	then
		echo "Run failed"
		exit 3
	fi
done

wait

echo "All processes completed"
echo "Starting Post-processing"

./visualizer $1 t
