#!/bin/bash

# Basic run script, expects two input arguments
# 	first one should be the name of the program being built by make
# 	The second is the number of steps this solver will run for


if [[ $# != 2 ]]
then
	echo "Not enough arguments, exiting ..."
	exit 1
fi

make $1

if [[ $? != 0 ]]
then
	echo "Make failed"
	exit 2
fi

rm -rf RESLT/*

dt=0.0001
nx=1000
tshift=0.0

for nx in 5 10 50 80 100 500 800 1000 5000 # 10000
# for dtp in -1 -2 -3 -4 -5
do
# 	dt=$(echo "10.0 ^ $dtp" | bc -l)
	# tsteps=$(echo "$2/$dt" | bc)
	echo -e "Running $1 with nx=$nx\t\tdt=$dt for $tsteps steps"
	./$1 --nx $nx --vardt --tshift $tshift --tsteps $2 >> RESLT/n$nx\_t$dt.stdout &
	# ./$1 --nx $nx --dt $dt --tshift $tshift --tsteps $2 >> RESLT/n$nx\_t$dt.stdout &

	if [[ $? != 0 ]]
	then
		echo "Run failed"
		exit 3
	fi
done

wait

echo "All processes completed"
echo "Starting Post-processing"

./visualizer $1 b
