#!/usr/bin/env python3

import subprocess
import sys

# from visualizer import Visualizer

class Run:
	def __init__(self, prog, nsteps, dxdt):
		self.prog = prog
		self.nsteps = nsteps
		self.dxdt = dxdt

		print(f'{self.prog=} {self.nsteps=} {self.dxdt=}')
	
	def build(self, dir, x, t):
		with open("Makefile", "r") as f:
			while line := f.readline():
				if line.startswith("CXXFLAGS"):
					flags = line.strip()
		flags = f'{flags} -DX_ORDER={x} -DT_ORDER={t}'
		print(flags)

		with open("build.stdout", "w") as f:
			subprocess.run(["make", self.prog, flags], check=True, stdout=f, stderr=subprocess.STDOUT)
		


if __name__ == '__main__':
	assert len(sys.argv) == 4

	run = Run(*sys.argv[1:])
	run.build("", 2, -1)